server:
  port: 8080


spring:
  datasource:
#    name: mysql_test
#    type: com.alibaba.druid.pool.DruidDataSource
#      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
      username: root
      password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xian.culturaland.entity

##pagehelper
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
#  returnPageInfo: check


